### ISSUE TITLE
Example of how this helps?

### ISSUE THREAD

**Issue by thunderkid** [nightwolfz/mobx-connect#1]
I'm sure this is my lack of knowledge, but I'm still trying to understand how this would make my code cleaner than just using `@observer`. Is there an example to show where `mobx-connect` would give an advantage over plain `mobx`? Thanks.

**Comment by osenvosem** [comment]
@thunderkid I think mobx-connect serve different purposes. Its purpose is passing data down the components tree and make it available in child components, but not to be an alternative to `@observer`. It may be useful for you if you want to pass, for example, a store from the top of components tree and get it inside any descendant component.

``` js
@connect
@observer
class App extends Component {
  render() {
    let { store } = this.context; // get it here
    //...
  }
}
```

**Comment by nightwolfz** [comment]
That's correct. It also makes the component observable by default without using `@observer`

For example, here's how you could work with simple ON/OFF toggles:

``` js
@connect
class Settings extends React.Component {

    setSetting(key) {
        const { settings} = this.context.state
        settings[key] = !settings[key]
    }

    render() {
        const { settings } = this.context.state

        return <div>
            <p>
                <a onClick={() => this.setSetting('fullscreen')}>
                    Turn {settings.fullscreen ? 'OFF' : 'ON'}
                </a>
            </p>
            <p>
                <a onClick={() => this.setSetting('logger')}>
                    Turn {settings.logger ? 'OFF' : 'ON'}
                </a>
            </p>
        </div>
    }
}
```

You can already see how this could simplify working with forms as well.

I usually put all of my state in a single file, giving you a nice overview of what your state looks like.

Ex:

``` js
const { observable, asReference, asFlat, toJSON } = require('mobx')

const defaultState = observable({
    app: {
        title: 'My Application',
        isMaximized: false
    },
    home: {
        menu: {
            index: 0,
            items: {}
        }
    },
    browse: {
        loading: false,
        items: asFlat([])
    },
    favorites: {
        loading: false,
        items: asFlat([])
    },
    search: {
        loading: false,
        text: '',
        suggestions: asReference([])
    },
    settings: {
        saveFiles: false
    }
})
```

**Comment by giacomorebonato** [comment]
I like the approach of having the state accessible from every component...
Which are the drawbacks? I am asking myself just because the [React documentation](https://facebook.github.io/react/docs/context.html) discourages to use context.

**Comment by nightwolfz** [comment]
@giacomorebonato context is not going away, too many libraries depend on it !

As for the drawbacks, one such would be that your components are now tightly coupled to your context.

This makes it somewhat harder to share your components as npm modules for example.
