### ISSUE TITLE
Module not found: Error: Cannot resolve module 'mobx-inferno'

### ISSUE THREAD

**Issue by arkist** [nightwolfz/mobx-connect#2]
latest commit https://github.com/nightwolfz/mobx-connect/commit/cf27a8dd6e2028d35e66fe97e79fa49e49bda41d makes Module not found Error.

**Comment by nightwolfz** [comment]
Thanks, fixed in the latest version.

You may have to `npm install mobx-react --save` as it's no longer part of dependencies now.
